const dotenv = require('dotenv');
const mongoose = require('mongoose');
const path = require('path');
const bcrypt = require('bcryptjs');

// Load environment variables from backend/.env
dotenv.config({ path: path.join(__dirname, '../.env') });

const connectDB = require('../config/db');
const { sendOtpEmail, sendInquiryEmail, sendEmail } = require('../utils/emailService');
const Ride = require('../models/Ride');
const User = require('../models/User');

async function runAgent1() {
  console.log('============================================================');
  console.log('🤖 AGENT 1: OTP VERIFICATION, MAIL DELIVERY, CONTACT FORM TEST');
  console.log('============================================================');

  try {
    // 1. Database Connection
    console.log('\n--- Step 1: Connecting to MongoDB ---');
    await connectDB();
    console.log('✅ Connected to MongoDB successfully.');

    // 2. SMTP Transporter & Mailbox Connectivity check
    console.log('\n--- Step 2: Testing SMTP Transporter Connectivity ---');
    const nodemailer = require('nodemailer');
    const transporter = nodemailer.createTransport({
      host: process.env.SMTP_HOST || 'smtp.gmail.com',
      port: parseInt(process.env.SMTP_PORT || '587'),
      secure: false,
      auth: {
        user: process.env.SMTP_USER,
        pass: process.env.SMTP_PASS,
      },
    });

    await new Promise((resolve, reject) => {
      transporter.verify((error, success) => {
        if (error) {
          console.error('❌ SMTP Connection Verification Failed:', error.message);
          reject(error);
        } else {
          console.log('✅ SMTP connection is verified and ready.');
          resolve();
        }
      });
    });

    // 3. Contact Form API/Service Test
    console.log('\n--- Step 3: Testing Contact Inquiry Email Dispatch ---');
    const mockInquiry = {
      firstName: 'Test',
      lastName: 'Agent1',
      email: 'engineering@devqor.in',
      phone: '+919999999999',
      subject: 'corporate',
      message: 'This is a test message generated by Agent 1 to check the contact form inquiry dispatch.'
    };
    
    const inquirySent = await sendInquiryEmail(mockInquiry);
    if (inquirySent) {
      console.log('✅ Contact Inquiry Email sent successfully!');
    } else {
      throw new Error('Contact Inquiry Email dispatch returned false');
    }

    // 4. Ride OTP Generation and Email Dispatch
    console.log('\n--- Step 4: Testing Ride OTP Email Dispatch ---');
    const mockRide = new Ride({
      client: new mongoose.Types.ObjectId(),
      pickupLocation: 'Salt Lake Sector V, Kolkata',
      dropoffLocation: 'Kolkata Airport (CCU)',
      pickupDate: '2026-06-25',
      pickupTime: '10:00',
      vehicleType: 'Mercedes E-Class',
      fare: 2500,
      paymentMethod: 'cash',
      passengerDetails: {
        fullName: 'Test Agent One',
        email: 'engineering@devqor.in',
        phone: '+919999999999'
      }
    });

    const testOtp = '8765';
    const driverName = 'John Chauffeur';
    
    const otpSent = await sendOtpEmail(mockRide, testOtp, driverName);
    if (otpSent) {
      console.log(`✅ OTP email containing code (${testOtp}) dispatched successfully to ${mockRide.passengerDetails.email}!`);
    } else {
      throw new Error('OTP email dispatch returned false');
    }

    // 5. OTP Hashing and Verification Check
    console.log('\n--- Step 5: Testing OTP Verification logic ---');
    const hashedOtp = await bcrypt.hash(testOtp, 10);
    const userInputCorrect = '8765';
    const userInputIncorrect = '1111';

    const isMatchCorrect = await bcrypt.compare(userInputCorrect, hashedOtp);
    const isMatchIncorrect = await bcrypt.compare(userInputIncorrect, hashedOtp);

    if (isMatchCorrect && !isMatchIncorrect) {
      console.log('✅ OTP hashing and comparison verification succeeded.');
    } else {
      throw new Error('OTP comparison validation failed!');
    }

    console.log('\n🎉 ALL AGENT 1 TESTS PASSED SUCCESSFULLY! 🎉');

  } catch (error) {
    console.error('\n❌ AGENT 1 RUN FAILED:', error.stack || error.message);
    process.exit(1);
  } finally {
    await mongoose.connection.close();
    console.log('\nDatabase connection closed. Agent 1 finished.');
  }
}

runAgent1();
